### ISSUE TITLE
XML parsing failure due to unescaped &

### ISSUE THREAD

**Issue by alexey-kudryavtsev** [savokiss/omnivore2rss#1]
First of all, thank you for your project, it's a huge boon for me and really helps me with my workflow.
I've encountered an error that I believe leads to invalid XML document and subsequently crushes XML parser.
When I GET `https://o2rss.detools.dev/public?token=<token>` everything works fine, but when I add more URL params (limit, query), e.g. `https://o2rss.detools.dev/public?token=<token>&limit=1`, I get an error like "This page contains the following errors:
error on line 7 at column 105: EntityRef: expecting ';'" 
The relevant part of the response is `<atom:link href="https://o2rss.detools.dev/public?token=<token>&limit=1" rel="self" type="application/rss+xml" />` I suppose XMLparser wants & to be escaped as `&amp;`

Some of the page links in my Omnivore.app also have `&` in their URL address. When these appear in the response, even a basic GET (https://o2rss.detools.dev/public?token=<token>) returns XML that crushes the parser. 

I guess this issue is just a matter of escaping/search&replace for links. 
Again I really appreciate your project and your help! Thanks.

**Comment by savokiss** [comment]
Yes, it seems there may be some unhandled characters. I'll check and fix it soon. 
Thanks for providing this feedback!

**Comment by savokiss** [comment]
Fixed 😊 You can try your own link. 
If there are any other issues, feel free to reopen it.

**Comment by alexey-kudryavtsev** [comment]
So far so good! Thanks a bunch 👍
